spring:
  datasource:
    url: jdbc:h2:mem:testdb;NON_KEYWORDS=USER
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: false
  sql:
    init:
      mode: always